version: "3.8"

services:
  postgres:
    image: postgres:15.1
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    volumes:
      - pgdata:/var/lib/postgresql/data

    ports:
      - 2908:5432

  redis:
    image: redis:7.0.5
  
  blog:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - SSLMODE=disable
      - SSL=true

      - HTTP_PORT=${HTTP_PORT}

      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}

      - SMTP_SENDER=${SMTP_SENDER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}

      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - media:/app/media
    depends_on:
      - postgres
    restart: always

volumes:
  pgdata:
  media:
